export const menuItems = [
  // fav
  {
    id: "suya-01",
    name: "Flame-Grilled Suya Skewers",
    price: 3000,
    category: "food",
    fav: true,
    image: "fav img/Nigerian Suya with Yaji Pepper.jfif",
  },
  {
    id: "coconut-rice-01",
    name: "Coconut Rice with Shrimp & Herbs",
    price: 4000,
    category: "food",
    fav: true,
    image: "fav img/Coconut rice.jfif",
  },
  {
    id: "turkey-01",
    name: "Pepper-Glazed Turkey Cutlets",
    price: 4500,
    category: "food",
    fav: true,
    image: "fav img/Turkey Cutlets.jfif",
  },
  {
    id: "asun-01",
    name: "Spicy Asun with Charred Peppers",
    price: 4500,
    category: "food",
    fav: true,
    image: "fav img/Asun.jfif",
  },
  {
    id: "shawarma-01",
    name: "Chicken Shawarma Wrap",
    price: 5000,
    category: "food",
    fav: true,
    image: "fav img/Chicken Shawarma.jfif",
  },
  {
    id: "rice-beef-01",
    name: "White Rice with Beef Stew",
    price: 4000,
    category: "food",
    fav: true,
    image: "fav img/Beef stew.jfif",
  },
  //   food
  {
    id: "burger-01",
    name: "Chicken Burger",
    price: 3000,
    category: "food",
    fav: false,
    image: "menu img/Burger.jfif",
  },
  {
    id: "jollof-01",
    name: "Jollof Rice and Chicken",
    price: 2000,
    category: "food",
    fav: false,
    image: "menu img/jollof rice and chicken.jfif",
  },
  {
    id: "pasta-01",
    name: "Creamy Chicken Pasta",
    price: 2000,
    category: "food",
    fav: false,
    image: "menu img/chicken pasta.jfif",
  },
  //   drinks
  {
    id: "coke-01",
    name: "Coca-cola",
    price: 500,
    category: "drinks",
    fav: false,
    image: "menu img/coke.jfif",
  },
  {
    id: "juice-01",
    name: "Fresh Orange Juice",
    price: 1000,
    category: "drinks",
    fav: false,
    image: "menu img/Orange juice.jfif",
  },
  //   desserts
  {
    id: "cake-01",
    name: "Chocolate Cake",
    price: 2300,
    category: "dessert",
    fav: false,
    image: "menu img/chocolate cake.jfif",
  },
  {
    id: "icecream-01",
    name: "Vanilla Ice Cream",
    price: 2400,
    category: "dessert",
    fav: false,
    image: "menu img/vanilla icecream.jfif",
  },
  //   snacks
  {
    id: "fries-01",
    name: "French Fries",
    price: 1800,
    category: "snacks",
    fav: false,
    image: "menu img/fries.jfif",
  },
  {
    id: "wings-01",
    name: "Chicken Wings",
    price: 3000,
    category: "snacks",
    fav: false,
    image: "menu img/chicken wings.jfif",
  },
];
